import http from 'node:http';
import {randomBytes,scrypt as sc,timingSafeEqual,createHmac} from 'node:crypto';
import {promisify} from 'node:util';
const scrypt=promisify(sc),port=Number(process.env.PORT||8787),secret=process.env.SESSION_SECRET||'dev-secret-change-me',provider=process.env.MODEL_PROVIDER||'mock';
if((process.env.NODE_ENV||'development')==='production'&&secret.length<32)throw new Error('SESSION_SECRET too short');
const users=new Map(),messages=new Map();
const agents=[
{id:'chief',name:'Diza Chief',role:'Coordinator'},
{id:'researcher',name:'Diza Researcher',role:'Researcher'},
{id:'operator',name:'Diza Operator',role:'Operator'}];
const b64=x=>Buffer.from(x).toString('base64url'),sign=x=>createHmac('sha256',secret).update(x).digest('base64url');
async function hp(p,s=randomBytes(16).toString('hex')){const d=await scrypt(String(p),s,64,{N:16384,r:8,p:1});return {s,h:Buffer.from(d).toString('hex')}}
function token(u){const p=b64(JSON.stringify({sub:u.id,username:u.username,exp:Math.floor(Date.now()/1000)+2592000}));return 'sess.'+p+'.'+sign(p)}
function verify(t=''){const[a,p,s]=String(t).split('.');if(a!=='sess'||!p||!s||sign(p)!==s)return null;try{const x=JSON.parse(Buffer.from(p,'base64url'));return x.exp>Math.floor(Date.now()/1000)?x:null}catch{return null}}
function user(req){const a=String(req.headers.authorization||'');return verify(a.startsWith('Bearer ')?a.slice(7):'')}
async function body(req){let b='';for await(const c of req){b+=c;if(b.length>1e6)throw new Error('too_large')}return b?JSON.parse(b):{}}
function send(res,n,o){res.writeHead(n,{'content-type':'application/json','cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(o))}
function nd(res,o){res.write(JSON.stringify(o)+'\n')}
const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b1020"><title>Diza Bot Agent</title><style>body{margin:0;background:#070a12;color:#eef3ff;font-family:system-ui}main{max-width:700px;margin:auto;padding:20px}input,button{font:inherit;padding:13px;border-radius:13px;border:1px solid #334;background:#10172a;color:#fff}button{background:linear-gradient(135deg,#34d6ff,#b65cff);color:#07111f;font-weight:800}.card{margin:15vh auto;max-width:380px;padding:22px;border:1px solid #28345d;border-radius:24px;background:#0d1426}.card>*{width:100%;box-sizing:border-box;margin:7px 0}#chat{padding-bottom:80px}.m{padding:12px 14px;border-radius:18px;margin:9px 0;max-width:85%;background:#111a31}.u{margin-left:auto;background:#3151c8}form{position:fixed;bottom:0;left:50%;transform:translateX(-50%);width:min(700px,100%);display:flex;gap:8px;padding:12px;background:#090d18}form input{flex:1}</style></head><body><main><h2>Diza Bot Agent</h2><div id="a" class="card"><input id="u" placeholder="Username"><input id="p" type="password" placeholder="Password"><button id="r">Register</button><button id="l">Login</button><small id="e"></small></div><div id="x" hidden><select id="g"></select><div id="chat"></div><form id="f"><input id="q" placeholder="Tulis pesan…"><button>Kirim</button></form></div></main><script>
let t=localStorage.diza||'',cur='chief';const H=()=>({'content-type':'application/json',...(t?{authorization:'Bearer '+t}:{})});async function api(p,o={}){let r=await fetch(p,{...o,headers:H()}),d=await r.json();if(!r.ok)throw Error(d.message||d.error);return d}function m(c,s){let d=document.createElement('div');d.className='m '+c;d.textContent=s;chat.append(d);return d}async function boot(){if(!t)return;try{let a=await api('/api/agents');g.innerHTML=a.map(x=>'<option value="'+x.id+'">'+x.name+'</option>').join('');aDiv.hidden=true;x.hidden=false}catch{t='';localStorage.removeItem('diza')}}const aDiv=document.getElementById('a');r.onclick=async()=>{try{let d=await api('/api/auth/register',{method:'POST',body:JSON.stringify({username:u.value,password:p.value})});t=d.token;localStorage.diza=t;boot()}catch(z){e.textContent=z.message}};l.onclick=async()=>{try{let d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:u.value,password:p.value})});t=d.token;localStorage.diza=t;boot()}catch(z){e.textContent=z.message}};g.onchange=()=>cur=g.value;f.onsubmit=async z=>{z.preventDefault();let s=q.value.trim();if(!s)return;q.value='';m('u',s);let b=m('','thinking…'),r=await fetch('/api/chat/stream',{method:'POST',headers:H(),body:JSON.stringify({agentId:cur,message:s})}),rd=r.body.getReader(),dc=new TextDecoder(),bf='',ans='';while(1){let{value,done}=await rd.read();if(done)break;bf+=dc.decode(value,{stream:true});let ls=bf.split('\n');bf=ls.pop();for(let L of ls)if(L){let E=JSON.parse(L);if(E.type==='delta'){ans+=E.delta;b.textContent=ans}}}};boot()</script></body></html>`;
const srv=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://x');if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,OPTIONS'});return res.end()}
if(req.method==='GET'&&url.pathname==='/api/health')return send(res,200,{ok:true,name:'Diza Bot Agent',version:'0.5.0',provider,persistence:'memory'});
if(req.method==='GET'&&url.pathname==='/') {res.writeHead(200,{'content-type':'text/html'});return res.end(html)}
if(req.method==='POST'&&url.pathname==='/api/auth/register'){const d=await body(req),un=String(d.username||'').trim().toLowerCase();if(!/^[a-z0-9._-]{3,32}$/.test(un)||String(d.password||'').length<8)return send(res,400,{error:'invalid_input',message:'Username 3-32 chars, password min 8 chars'});if(users.has(un))return send(res,409,{error:'exists'});const {s,h}=await hp(d.password),u={id:crypto.randomUUID(),username:un,s,h};users.set(un,u);return send(res,201,{token:token(u),user:{id:u.id,username:u.username}})}
if(req.method==='POST'&&url.pathname==='/api/auth/login'){const d=await body(req),u=users.get(String(d.username||'').trim().toLowerCase());if(!u)return send(res,401,{error:'invalid_credentials'});const {h}=await hp(d.password,u.s),A=Buffer.from(h,'hex'),B=Buffer.from(u.h,'hex');if(A.length!==B.length||!timingSafeEqual(A,B))return send(res,401,{error:'invalid_credentials'});return send(res,200,{token:token(u),user:{id:u.id,username:u.username}})}
const me=user(req);if(url.pathname.startsWith('/api/')&&!me)return send(res,401,{error:'user_session_required'});
if(req.method==='GET'&&url.pathname==='/api/agents')return send(res,200,agents);
if(req.method==='POST'&&url.pathname==='/api/chat/stream'){const d=await body(req),a=agents.find(x=>x.id===d.agentId)||agents[0],msg=String(d.message||'').trim();if(!msg)return send(res,400,{error:'message_required'});res.writeHead(200,{'content-type':'application/x-ndjson','cache-control':'no-store'});nd(res,{type:'start',agentId:a.id});let out='';if(msg.startsWith('/time'))out=new Date().toISOString();else if(msg.startsWith('/delegate ')){const [,id,...rest]=msg.split(' '),ta=agents.find(x=>x.id===id);out=ta?'Delegated to '+ta.name+': '+rest.join(' '):'Agent not found'}else out='['+a.name+'] Diza Bot Agent online. Provider '+provider+'. Kamu bilang: '+msg;for(const w of out.match(/\S+\s*/g)||[out])nd(res,{type:'delta',delta:w});nd(res,{type:'done',meta:{agentId:a.id}});return res.end()}
return send(res,404,{error:'not_found'})}catch(e){console.error(e);if(!res.headersSent)send(res,500,{error:'internal_error'});else res.end()}});
srv.listen(port,'0.0.0.0',()=>console.log('Diza Bot Agent online on '+port));